server:
  port: 8000

spring:
  application:
    name: "minio-service"

  servlet:
    multipart:
      max-file-size: 50000MB
      max-request-size: 50000MB

# Minio Config
minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin123
  bucket-name: mybucket
